### ISSUE TITLE
How to set this up

### ISSUE THREAD

**Issue by pixelass** [dadoagency/dado-aa-contentful-app#13]
We found this extension and think it might be what we're looking for. Sadly we don*'t k now how to set it up in contentful. 

Can you add a step-by-step guide for the setup?

Thank you in advance.

**Comment by S-codes14** [comment]
@pixelass it is react, all you need to do is install nodejs from nodejs.org. then run npm install then npm start

**Comment by pixelass** [comment]
> @pixelass it is react, all you need to do is install nodejs from nodejs.org. then run npm install then npm start

Sorry but this is neither helpful nor an answer to my question. 
I asked how to integrate this in Contentful.

Closing, since we no longer need it and the repo owners don't seem to maintain it anymore
